### ISSUE TITLE
Unsatisfiable requirements detected for package

### ISSUE THREAD

**Issue by veroyatnost** [m-dadej/MarSwitching.jl#7]
Hi, I am looking forward to using `MarSwitching.jl` for developing a forecast model. However, during my installation, the error was thrown.

`ERROR: Unsatisfiable requirements detected for package MarSwitching [b2b8a7f1]:
 MarSwitching [b2b8a7f1] log:
 ├─possible versions are: 0.1.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.1
 └─restricted by compatibility requirements with NLopt [76087f3c] to versions: uninstalled — no versions left
   └─NLopt [76087f3c] log:
     ├─possible versions are: 0.5.0-1.0.0 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions: 0.5.0-1.0.0
     └─restricted by compatibility requirements with QuantEcon [fcd29c91] to versions: 0.5.0-0.6.5
       └─QuantEcon [fcd29c91] log:
         ├─possible versions are: 0.14.3-0.16.5 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions: 0.14.3-0.16.5`

And the version of local packages are
  "VegaLite"                 => v"3.2.3"
  "Query"                    => v"1.0.0"
  "UpdateJulia"              => v"0.4.2"
  "NLopt"                    => v"0.6.5"
  "LaTeXStrings"             => v"1.3.0"
  "MixedModels"              => v"4.22.1"
  "StructuralEquationModels" => v"0.2.1"
  "IJulia"                   => v"1.24.2"
  "Plots"                    => v"1.39.0"
  "Metal"                    => v"0.5.1"
  "Pluto"                    => v"0.19.30"
  "DataFrames"               => v"1.3.6"
  "UnicodePlots"             => v"3.6.0"
  "QuantEcon"                => v"0.16.5"

Will  the later version meeting the satisfaction of latest packages?

Thanks!

**Comment by m-dadej** [comment]
Thanks for opening this issue!

I see the QuantEcon.jl requires NLopt.jl to be between 0.5.0 and 0.6.5. I reproduced your error and after downgrading package requirements for NLopt to ">= 0.6.5" it should work.

I will soon release new version to the Julia's general registry with other improvements. Meanwhile you may use:
`] add MarSwitching#main`
This will install the github version of the package with the changes. Tell me if it works.

**Comment by veroyatnost** [comment]
> Thanks for opening this issue!
> 
> I see the QuantEcon.jl requires NLopt.jl to be between 0.5.0 and 0.6.5. I reproduced your error and after downgrading package requirements for NLopt to ">= 0.6.5" it should work.
> 
> I will soon release new version to the Julia's general registry with other improvements. Meanwhile you may use: `] add MarSwitching#main` This will install the github version of the package with the changes. Tell me if it works.

Hi! Thank you for your quick reply.

However, I have tried several times. It seems the conflicting packages are MarSwitching and QuantEcon. The following codes could install the package properly.
`julia
] rm QuantEcon
resolve
add MarSwitching
`
And, after `MarSwitching` installed,  the `QuantEcon` is not able to be installed anymore.

Considering the popular usage of `QuantEcon`, I am looking forward to the update of `MarSwitching`.

Thanks for your contribution and share it~

**Comment by m-dadej** [comment]
Yes, the general registry version of MarSwitching.jl has old compatibilities. I just changed dependency requirements in github version and will release this version to the general registry soon.

In the meantime you may try installing the github version and see if it still conflicts with QuantEcon:

`] add MarSwitching#main`

Tell me if this one works.

**Comment by veroyatnost** [comment]
> Yes, the general registry version of MarSwitching.jl has old compatibilities. I just changed dependency requirements in github version and will release this version to the general registry soon.
> 
> In the meantime you may try installing the github version and see if it still conflicts with QuantEcon:
> 
> `] add MarSwitching#main`
> 
> Tell me if this one works.

Sorry for delay reply, and this works. Thank you for your contribution!
