### ISSUE TITLE
No df_spx.csv in repo files

### ISSUE THREAD

**Issue by PharmCat** [m-dadej/MarSwitching.jl#8]
There is no df_spx.csv and no reference to public download resources where file can be found.

**Comment by m-dadej** [comment]
Thanks for letting me know! I added the csv file to the repository and referenced it in the documentation. It's from yahoo finance. Commit: https://github.com/m-dadej/MarSwitching.jl/commit/7e0af868baf30c36dcce3dd18c33f150f877e4f7
